on:
  workflow_dispatch:
  push:
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test via install
        uses: JJ/raku-test-action@v2
